services:
  nginx:
    labels:
      - traefik.enable=true
      - traefik.http.services.${NETWORK_NAME}.loadbalancer.server.port=80
      - traefik.http.routers.${NETWORK_NAME}.rule=Host(`${DOMAIN}.w1vern.space`)
      - traefik.http.routers.${NETWORK_NAME}.entrypoints=https
      - traefik.http.routers.${NETWORK_NAME}.tls.certresolver=letsEncrypt
    networks:
      default:
      traefik_traefik:
    ports: []

networks:
  traefik_traefik:
    external: true